CommunitySpaceShip/Controllers/UserAdminController.cs
using CommunitySpaceShip.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CommunitySpaceShip.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersAdminController : Controller
    {
        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }

        //
        // GET: /Users/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        //
        // GET: /Users/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = userViewModel.Email, Email = userViewModel.Email };
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,Id")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.Email;
                user.Email = editUser.Email;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        //
        // GET: /Users/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /Users/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

CommunitySpaceShip/Views/UsersAdmin/Create.cshtml
@model CommunitySpaceShip.Models.RegisterViewModel
@{
    ViewBag.Title = "Create New User";
}

<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-white font-weight-bold">@ViewBag.Title</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-10 align-self-start text-white">
                @using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary("", new { @class = "text-error" })
                    <div class="form-group">
                        @Html.LabelFor(m => m.DisplayName, new { @class = "control-label" })
                        <div class="col-12 offset-0 col-md-10 offset-md-1">
                            @Html.TextBoxFor(m => m.DisplayName, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Email, new { @class = "control-label" })
                        <div class="col-12 offset-0 col-md-10 offset-md-1">
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Password, new { @class = "control-label" })
                        <div class="col-12 offset-0 col-md-10 offset-md-1">
                            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "control-label" })
                        <div class="col-12 offset-0 col-md-10 offset-md-1">
                            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <span class="col-12 offset-0 col-md-10 offset-md-1">
                            Role:
                            @foreach (var item in (SelectList)ViewBag.RoleId)
                            {
                                <span class="p-2">
                                    <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline" />
                                    @Html.Label(item.Value, new { @class = "control-label" })
                                </span>
                            }
                        </span>
                    </div>
                    <div class="form-group">
                        <div class="col-12 offset-0 col-md-10 offset-md-1">
                            <input type="submit" class="btn btn-xl myBtn mb-3" value="Create User" />
                            <br />
                            @Html.ActionLink("Back to Users", "Index", routeValues: null, htmlAttributes: new { @class = "myLink" })
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</header>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CommunitySpaceShip/Views/UsersAdmin/Delete.cshtml
@model CommunitySpaceShip.Models.ApplicationUser

@{
    ViewBag.Title = "Delete User";
}

<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-white font-weight-bold">@ViewBag.Title</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-10 align-self-start text-white">
                <h3>Are you sure you want to delete this User?</h3>
                <div>
                    <h2 class="mb-3">
                        @Html.DisplayFor(model => model.UserName)
                    </h2>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Delete" class="btn btn-xl myBtn mb-3" />
                            <br />
                            @Html.ActionLink("Back to Users", "Index", routeValues: null, htmlAttributes: new { @class = "myLink" })
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</header>

CommunitySpaceShip/Views/UsersAdmin/Details.cshtml
@model CommunitySpaceShip.Models.ApplicationUser

@{
    ViewBag.Title = "Details";
}

<h2>Details.</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>
</div>
<h4>List of roles for this user</h4>
@if (ViewBag.RoleNames.Count == 0)
{
    <hr />
    <p>No roles found for this user.</p>
}

<table class="table">

    @foreach (var item in ViewBag.RoleNames)
    {
        <tr>
            <td>
                @item
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CommunitySpaceShip/Views/UsersAdmin/Edit.cshtml
@model CommunitySpaceShip.Models.EditUserViewModel

@{
    ViewBag.Title = "Edit Users";
}

<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-white font-weight-bold">@ViewBag.Title</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-10 align-self-start">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal text-white">
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, new { @class = "control-label" })
                        <div class="col-md-10 offset-md-1">
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Email)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.DisplayName, new { @class = "control-label" })
                        <div class="col-md-10 offset-md-1">
                            @Html.TextBoxFor(m => m.DisplayName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Email)
                        </div>
                    </div>

                    <div class="form-group">
                        <span class=" col-md-10 offset-md-1">
                            @Html.Label("Roles: ", new { @class = "control-label" })
                            @foreach (var item in Model.RolesList)
                            {
                                <span class="p-2">
                                    <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                                    @Html.Label(item.Value, new { @class = "control-label" })
                                </span>
                            }
                        </span>
                    </div>

                    <div class="form-group">
                        <div class="offset-md-1 col-md-10">
                            <input type="submit" value="Save" class="btn btn-xl myBtn mb-3" />
                            <br />
                            @Html.ActionLink("Back to Users", "Index", routeValues: null, htmlAttributes: new { @class = "myLink" })
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
    </div>
</header>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CommunitySpaceShip/Views/UsersAdmin/Index.cshtml
@model IEnumerable<CommunitySpaceShip.Models.ApplicationUser>

@{
    ViewBag.Title = "Users Admin";
}


<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-white font-weight-bold">@ViewBag.Title</h1>
                <hr class="divider my-4" />
            </div>
            <div class="col-lg-10 align-self-start">
                <p>
                    @Html.ActionLink("Create New User", "Create", routeValues: null, htmlAttributes: new { @class = "myLink" })
                </p>
                <table class="table text-white">
                    <tr>
                        <th>
                            User Name
                        </th>
                        <th>

                        </th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserName)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, htmlAttributes: new { @class = "myLink" }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, htmlAttributes: new { @class = "myLink" })
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>
    </div>
</header>